### ISSUE TITLE
concat error Error: failed to create OpenGL context

### ISSUE THREAD

**Issue by mavrovgeorgi** [transitive-bullshit/ffmpeg-concat#37] opened 2019-01-27 01:15 UTC
Hello!

I deployed my application on an **Ubuntu 18.04 remote Server** and than acuered the following error when adding the transitions. 
I tried to configure everything properly. Have mesa installed..

`concat error Error: failed to create OpenGL context
(node:31455) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:31455) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I found similar issues here and tried everything, but I am still not able to fix it..
I would be very thankful to any suggestions from you!

**Comment by daniel-habib** [comment] 2019-02-16 17:17
have you tried doing something like 
`xvfb-run -s "-ac -screen 0 1280x1024x24" node <your script>`
?

**Comment by xjqxz2** [comment] 2019-02-28 01:49
In Ubuntu server ,Must be use  xvfb-run -s "-ac -screen 0 1280x1024x24" ? How can I not use it?

**Comment by transitive-bullshit** [comment] 2019-03-11 00:50
duplicate of https://github.com/transitive-bullshit/ffmpeg-concat/issues/36

**Closed by transitive-bullshit** 2019-03-11 00:50 UTC
